### ISSUE TITLE
Can't install it?

### ISSUE THREAD

**Issue by thomasleitner** [tess1o/go-ecoflow#9]
Sorry, but i'm a beginner with "go" ... but I've got lots of Linux experience -- still I cannot get it installed.
I'm running debian 12.4, installed go manually into /usr/local/go.   Go is at version 1.22.5:

```
pi@openwb-if:~$ go version
go version go1.22.5 linux/amd64
pi@openwb-if:~$ go install github.com/tess1o/go-ecoflow@latest
go: downloading github.com/tess1o/go-ecoflow v1.1.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.4.3
go: downloading github.com/google/uuid v1.6.0
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading golang.org/x/net v0.8.0
go: downloading golang.org/x/sync v0.1.0
package github.com/tess1o/go-ecoflow is not a main package
pi@openwb-if:~$ go run test.go
test.go:5:2: cannot find package "github.com/tess1o/go-ecoflow" in any of:
        /usr/local/go/src/github.com/tess1o/go-ecoflow (from $GOROOT)
        /home/pi/go/pkg/mod/src/github.com/tess1o/go-ecoflow (from $GOPATH)
```

It's apparently installed differently as expected:

```
pi@openwb-if:~$ ls /home/pi/go/pkg/mod/
pkg
pi@openwb-if:~$ ls /home/pi/go/pkg/mod/
pkg
pi@openwb-if:~$ ls /home/pi/go/pkg/mod/pkg
mod  sumdb
pi@openwb-if:~$ ls /home/pi/go/pkg/mod/pkg/mod
cache  github.com  golang.org
```

There is no "src" subdirectory here ...   GOPATH is:

```
pi@openwb-if:~$ go env | grep GOPATH
GOPATH='/home/pi/go'
```

"test.go" is the example from your documentation ... 

Sorry for the real basic question here ... Thanks!

**Comment by tess1o** [comment]
Hello,

If you want to add this library you your project just use: `go get github.com/tess1o/go-ecoflow` in your project folder.

`pi@openwb-if:~$ go run test.go` - not sure what you're trying to do... There is no "test.go" in this project.

**Comment by thomasleitner** [comment]
Yes, sorry ... I've managed now to run a test program with your library. Thanks a lot -- fault all on my side.

As an aside: Do you have a code to simply output the JSON received via the REST API?

Or can your exporter software also export to text file or stdout?

**Comment by tess1o** [comment]
A sample is below: 
1. Create a client
2. Get all parameters from your device: `params := client.GetDeviceAllParameters(context.Background(), "DEVICE_SERIAL_NUMBER")`
3. Marshal to json: ` jsonParams, err := json.Marshal(params )`
4. Then you can save the json to a file, print in to stdout, etc.

```
package main

import (
	"context"
	"github.com/tess1o/go-ecoflow"
        "json"
	"log/slog"
	"os"
)

func main() {
	slog.SetLogLoggerLevel(slog.LevelDebug)
	accessKey := os.Getenv("ACCESS_KEY")
	secretKey := os.Getenv("SECRET_KEY")

	if accessKey == "" || secretKey == "" {
		slog.Error("AccessKey and SecretKey are mandatory")
		return
	}

	//create new client.
	client := ecoflow.NewEcoflowClient(accessKey, secretKey)

	// get all parameters for one device as map[string]interface{}
	params := client.GetDeviceAllParameters(context.Background(), "DEVICE_SERIAL_NUMBER")
        jsonParams, err := json.Marshal(params )
}
```

You can also get all linked devices: `devices := client.GetDeviceList(context.Background())` and use their serial number to fetch the parameters (in a loop).

**Comment by thomasleitner** [comment]
Super --- Thanks a lot ... I'll try that!

**Comment by tess1o** [comment]
Closing this issue since it was an installation issue on the user side.
